dataset:
  name: MNIST

architecture:
  backbone: MLPvanilla

hyperparams:
  train:
    batch_size: 64
    epochs: 101
    lr: 0.0001
    loss_pen_factor: 10
    logging_pen: 0
    logging: 5
    step_scheduler: 5
    samples: 3
  architecture:
    backbone_dense_nodes: 2048
    pen_nodes: 64

path:
  metrics_dir: ./results

